version: '3.8'

services:
  web:
    container_name: fastapi_app_redis 
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - 6379:6379
    restart: always